package com.mohammedragab.domainlayer.entities

data class TotalNutrients(
    val CA: MainFeatureData,
    val CHOCDF: MainFeatureData,
    val CHOLE: MainFeatureData,
    val ENERC_KCAL: MainFeatureData,
    val FAMS: MainFeatureData,
    val FAPU: MainFeatureData,
    val FASAT: MainFeatureData,
    val FAT: MainFeatureData,
    val FE: MainFeatureData,
    val FIBTG: MainFeatureData,
    val FOLAC: MainFeatureData,
    val FOLDFE: MainFeatureData,
    val FOLFD: MainFeatureData,
    val K: MainFeatureData,
    val MG: MainFeatureData,
    val NA: MainFeatureData,
    val NIA: MainFeatureData,
    val P: MainFeatureData,
    val PROCNT: MainFeatureData,
    val RIBF: MainFeatureData,
    val SUGAR: MainFeatureData,
    val THIA: MainFeatureData,
    val TOCPHA: MainFeatureData,
    val VITA_RAE: MainFeatureData,
    val VITB12: MainFeatureData,
    val VITB6A: MainFeatureData,
    val VITC: MainFeatureData,
    val VITD: MainFeatureData,
    val VITK1: MainFeatureData,
    val WATER: MainFeatureData,
    val ZN: MainFeatureData
)